Update playground, and also update realtime audio visualizer and realtime chat.
outspeed-ai/outspeed-js pull request #3
Opened 2024-09-21 15:33 UTC by ankit-adapt

# Summary

In this PR we have redesigned the playground from scratch. In order to do this, we have also updated some of our realtime components.

# Changes

1. Update Realtime Visualizer. Remove dependency from `audiomotion-analyzer`.
2. Update Realtime Chat component.
3. Redesign the playground.
4. Remote react-router. (Will add some routing solution later.)

# Testing

1. Tested WebRTC example locally.
2. Tested WebSocket example locally.

# Note

In this PR if you try to send message in websocket example, it will not work. This will be fixed by #2 
Also, won't able to check WebRTC send message feature. Maybe after merging #2 we can test it.

2024-09-22 22:33 UTC, janak2 commented
1. You can run the webrtc example without selecting a audio or video device. One of them should be selected.
2. The audiovisualizer is not placed correctly:
<img width="1567" alt="Screenshot 2024-09-22 at 3 26 52 PM" src="https://github.com/user-attachments/assets/a212ff7a-0161-43dd-8bff-a99ebddad071">

2024-09-22 22:40 UTC, janak2 commented
The chat should open in a side panel similar to how it works in google meets:

<img width="1552" alt="Screenshot 2024-09-22 at 3 39 32 PM" src="https://github.com/user-attachments/assets/967f0575-d5b5-4eef-a45f-b3398525ea43">
<img width="1679" alt="Screenshot 2024-09-22 at 3 40 22 PM" src="https://github.com/user-attachments/assets/5fbddb4d-7b53-4555-827d-19d0dcdb6692">

2024-09-23 02:38 UTC, janak2 commented
Increase size of github and docs button

2024-09-23 04:46 UTC, altairmn requested changes

2024-09-23 04:46 UTC, altairmn commented on examples/playground-js/public/outspeed.svg
use the logo version that works on dark background

2024-09-23 04:46 UTC, altairmn commented on examples/playground-js/src/App.tsx
make the pages responsive.

2024-09-23 13:55 UTC, ankit-adapt commented
@janak2 

> You can run the webrtc example without selecting a audio or video device. One of them should be selected.

Add a basic form validation logic. Now, we are checking whether audio or video device is selected. If not, then we are showing an error.

> The audiovisualizer is not placed correctly:

Make audio visualizer responsive.

2024-09-23 13:57 UTC, ankit-adapt commented on examples/playground-js/public/outspeed.svg
@altairmn Updated the logo.

2024-09-23 13:57 UTC, ankit-adapt commented on examples/playground-js/src/App.tsx
Now pages are responsive.

2024-09-25 06:09 UTC, altairmn commented on packages/core/src/RealtimeWebSocket/RealtimeWebSocketConnection.ts
> +    console.log("So", response.data);
What's this line?

2024-09-25 06:15 UTC, ankit-adapt commented on packages/core/src/RealtimeWebSocket/RealtimeWebSocketConnection.ts
> +    console.log("So", response.data);
Removed! I was testing locally and forgot to remove this log.

2024-09-25 06:54 UTC, altairmn approved these changes

2024-09-25 06:59 UTC, merged